apiVersion: v2
appVersion: latest
description: Helm chart to deploy Stardog Voicebox service
home: https://stardog-union.github.io/kube-stardog-stack/
icon: https://raw.githubusercontent.com/stardog-oss/.github/main/assets/stardog_open_source_light.svg
maintainers:
- email: oss@stardog.com
  name: Stardog Open-Source Community
  url: https://www.stardog.com
name: voicebox
version: 1.2.0
dependencies:
- name: common
  version: 0.1.7
  repository: file://../common
