{{- if and .Values.stardog.metricsEnabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sdcommon.fullname" . }}-stardog
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    {{- with .Values.stardog.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ default .Release.Namespace .Values.stardog.namespace | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/name: stardog
  endpoints:
    - port: http
      path: {{ .Values.stardog.metricsPath }}
      interval: {{ .Values.stardog.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.stardog.serviceMonitor.scrapeTimeout }}
{{- end }}
