{{- if and .Values.metrics.enabled (eq .Values.metrics.auth.type "basicAuth") (eq .Values.metrics.auth.basicAuth.existingSecret "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdcommon.fullname" . }}-metrics-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sdcommon.labels.standard" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.metrics.auth.basicAuth.username | b64enc }}
  password: {{ .Values.metrics.auth.basicAuth.password | b64enc }}
{{- end }}
