{{- if and (hasKey .Values "image") .Values.image.username .Values.image.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-image-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sdcommon.labels.standard" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" .  }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdcommon.fullname" . }}-password
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sdcommon.labels.standard" . | nindent 4 }}
type: Opaque
data:
  password: {{ b64enc .Values.admin.password }}

---

{{- if and .Values.backup.enabled .Values.backup.location.azure.enabled }}
{{- if and .Values.backup.location.azure.accountName .Values.backup.location.azure.accountKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backup-azure-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sdcommon.labels.standard" . | nindent 4 }}
type: Opaque
data:
  accountname: {{ .Values.backup.location.azure.accountName  | b64enc }}
  accountkey: {{ .Values.backup.location.azure.accountKey | b64enc }}

{{- end }}
{{- end }}


{{- if and .Values.backup.enabled (not .Values.backup.backupCredentialsSecret) }}
---
{{- $password := randAlphaNum 12 }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace ((include "sdcommon.fullname" .) | printf "%s-backup-credentials") }}

{{- if not $existing }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ ((include "sdcommon.fullname" .) | printf "%s-backup-credentials") }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{ include "sdcommon.labels.standard" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.backup.credentials.username  | b64enc }}
  password: {{ .Values.backup.credentials.password | default $password | b64enc }}
{{- end }}
{{- end }}

{{- if and .Values.backup.enabled .Values.backup.location.s3.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backup-s3-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "sdcommon.labels.standard" . | nindent 4 }}
type: Opaque
data:
  bucketName: {{ .Values.backup.location.s3.bucketName  | b64enc }}
  region: {{ .Values.backup.location.s3.region | b64enc }}
  accessKey: {{ .Values.backup.location.s3.accessKey | b64enc }}
  secretKey: {{ .Values.backup.location.s3.secretKey | b64enc }}
{{- end }}

