apiVersion: v2
appVersion: latest
description: Helm chart to deploy Stardog Launchpad
home: https://stardog-union.github.io/kube-stardog-stack/
icon: https://s3.amazonaws.com/stardog-logos.public/stardog-logo.png
maintainers:
- email: oss@stardog.com
  name: Stardog Open-Source Community
  url: https://www.stardog.com
name: launchpad
version: 1.0.1
dependencies:
- name: common
  version: 0.1.5
  repository: file://../common
