{{- if and (hasKey .Values "image") .Values.image.username .Values.image.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cachetarget.fullname" . }}-image-pull-secret
  namespace: {{ include "cachetarget.namespace" . }}
  labels:
    {{- include "sdcommon.labels.standard" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "sdcommon.imagePullSecret" . }}
---
{{- end }}
{{- if (not .Values.admin.passwordSecretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cachetarget.fullname" . }}-password
  namespace: {{ include "cachetarget.namespace" . }}
  labels:
    {{- include "sdcommon.labels.standard" . | nindent 4 }}
type: Opaque
data:
  password: {{ b64enc .Values.admin.password }}
{{- end }}
