{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cachetarget.fullname" . }}
  namespace: {{ include "cachetarget.namespace" . }}
  labels:
    app: {{ include "cachetarget.fullname" . }}
    {{- include "sdcommon.labels.standard" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
