{{- $envVars := .Values.environmentVariables | default (dict) -}}
{{- $tmpDir := get $envVars "TMPDIR" | default "/tmp" -}}
{{- $vbxConfigFile := get $envVars "VBX_CONFIG_FILE" | default "/voicebox-config/vbx_config.json" -}}
{{- $vbxBitesConfigFile := get $envVars "VBX_BITES_CONFIG_FILE" | default "/bites-voicebox-config/vbx_bites_config.yaml" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdcommon.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdcommon.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "sdcommon.labels.selector" . | nindent 6 }}
      app: {{ include "sdcommon.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "sdcommon.fullname" . }}
        {{ include "sdcommon.labels.standard" . | nindent 8 }}
      annotations:
        checksum/config: {{ include "voicebox.configmapChecksum" . }}
        checksum/secret: {{ include "voicebox.secretChecksum" . }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- if and (hasKey .Values "image") .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
  {{- if and (hasKey .Values "image") .Values.image.username .Values.image.password }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-voicebox-image-pull-secret
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccountName | default "voicebox-sa" }}
      containers:
        - name: {{ include "sdcommon.fullname" . }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          securityContext: 
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: {{ (index .Values.ports 0).name }}
              containerPort: {{ include "voicebox.servicePort" . | int }}
              protocol: TCP
          env:
            - name: VBX_CONFIG_FILE
              value: {{ $vbxConfigFile | quote }}
            - name: TMPDIR
              value: {{ $tmpDir | quote }}
          {{- if .Values.bitesService.enabled }}
            - name: VBX_BITES_CONFIG_FILE
              value: {{ $vbxBitesConfigFile | quote }}
          {{- end }}
          {{- range $key, $value := $envVars }}
          {{- if and (ne $key "TMPDIR") (ne $key "VBX_CONFIG_FILE") (ne $key "VBX_BITES_CONFIG_FILE") }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: http
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}          
          volumeMounts:
            - name: tmp
              mountPath: {{ $tmpDir | quote }}
            - name: {{ include "sdcommon.fullname" . }}
              mountPath: {{ $vbxConfigFile | quote }}
              subPath: vbx_config.json
              readOnly: true
            {{- if .Values.bitesService.enabled }}
            - name: {{ include "sdcommon.fullname" . }}-bites-config
              mountPath: {{ $vbxBitesConfigFile | quote }}
              subPath: vbx_bites_config.yaml
              readOnly: true
            {{- end }}
          {{- with .Values.resources }}
          resources:
          {{- toYaml . | nindent 12}}
          {{- end }}
      {{- with include "sdcommon.podScheduling" . }}
{{ . | nindent 6 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: {{ include "sdcommon.fullname" . }}
            topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{ include "sdcommon.fullname" . }}
              topologyKey: topology.kubernetes.io/zone
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: {{ include "sdcommon.fullname" . }}
          configMap:
            name: {{ include "sdcommon.fullname" . }}
            items:
              - key: vbx_config.json
                path: vbx_config.json
      {{- if .Values.bitesService.enabled }}
        - name: {{ include "sdcommon.fullname" . }}-bites-config
          configMap:
            name: {{ include "sdcommon.fullname" . }}-bites-config
            items:
              - key: vbx_bites_config.yaml
                path: vbx_bites_config.yaml
      {{- end }}
