{{- if and (hasKey .Values "image") .Values.image.username .Values.image.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-voicebox-image-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdcommon.labels.standard" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "voiceboximagePullSecret" . }}
{{- end }}
