apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName | default "voicebox" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdcommon.labels.standard" . | nindent 4 }}
{{- if .Values.bitesService.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: voicebox-bites-service-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdcommon.labels.standard" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
    verbs: ["create", "get", "list", "delete", "deletecollection", "update", "watch"]
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications"]
    verbs: ["create", "get", "list", "delete", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: voicebox-bites-service-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sdcommon.labels.standard" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: voicebox-bites-service-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}