name: CI (features)

on:
  push:
    branches:
      - 'SAT-*'
      - 'CLOUD-*'
      - '!SAT-*-release'
      - '!SAT-*-release-*'
      - '!SAT-*-hotfix'
      - '!SAT-*-hotfix-*'
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/helm-validate-reusable.yml
    with:
      charts: '["charts/stardog","charts/zookeeper","charts/launchpad","charts/gateway","charts/voicebox","charts/cachetarget","."]'

  # smoke:
  #   needs: unit-tests
  #   uses: ./.github/workflows/minikube-smoke.yml
  #   secrets: inherit
