name: CI (main)

on:
  push:
    branches: [ main ]

jobs:
  validate:
    uses: ./.github/workflows/helm-validate-reusable.yml
    with:
      charts: '["charts/stardog","charts/zookeeper","charts/launchpad","charts/voicebox","charts/cachetarget","."]'

  # smoke:
  #   needs: validate
  #   uses: ./.github/workflows/minikube-smoke.yml
  #   secrets: inherit

  ci:
    needs: validate
    uses: ./.github/workflows/helm-package-reusable.yml
    secrets: inherit
    with:
      charts: '["charts/stardog","charts/zookeeper","charts/launchpad","charts/voicebox","charts/cachetarget","."]'
      oci_repo: 'oci://stardog-example-helm-chart.jfrog.io/'
      versioning_mode: 'release'
