name: CI (main)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    uses: ./.github/workflows/helm-validate-reusable.yml
    with:
      charts: '["charts/stardog","charts/zookeeper","charts/launchpad","charts/gateway","charts/voicebox","charts/cachetarget","."]'
