name: Release (tags)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  validate:
    if: ${{ github.actor != 'github-actions[bot]' }}
    uses: ./.github/workflows/helm-validate-reusable.yml
    with:
      charts: '["charts/stardog","charts/zookeeper","charts/launchpad","charts/gateway","charts/voicebox","charts/cachetarget","."]'

  release:
    if: ${{ github.actor != 'github-actions[bot]' }}
    needs: validate
    uses: ./.github/workflows/helm-github-release.yml
    with:
      charts: '["charts/stardog","charts/zookeeper","charts/launchpad","charts/gateway","charts/voicebox","charts/cachetarget","."]'
      release_tag: ${{ github.ref_name }}
